### PR TITLE
Removed abstract class declaration from freezed templates

### PR DESCRIPTION
**Pull request by fnicastri**
Just removed the abstract declaration from the templates

### CODE REVIEW

**Comment by tbm98** [comment]
Hi @fnicastri .
I think we should keep the old snippet for olders version before freezer 0.14.0, and clone it into a new snippet with another name like `Freezed14` and  `freezedWithoutImport14` and update the description for it. I know still have too many people who don't migrate to flutter 2 yet.

**Comment by fnicastri** [comment]
What about feezed/freezedAbstract and freezedWithoutImport/freezedAbstractWithoutImport?
Just an idea

**Comment by tbm98** [comment]
It looks good too @fnicastri

**Comment by tbm98** [comment]
LGTM!
I will publish a new version soon.

**Comment by tbm98** [comment]
Thanks for your help ;D @fnicastri

**Comment by fnicastri** [comment]
@tbm98 thank you for this plugin!

**Pull request merged**
